name: Daily Script

on:
  schedule:
    - cron: "20 10 * * 1-5"  # Runs at 3:50 AM UTC daily

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    env:  # Add secrets as environment variables
      MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      API_KEY_GEN: ${{ secrets.API_KEY_GEN }}
      API_KEY_GEN_2: ${{ secrets.API_KEY_GEN_2 }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install dependencies
      run: |
          pip install requests
          pip install beautifulsoup4
          pip install python-dotenv
          pip install google-generativeai
          pip install fpdf
          pip install playwright

    - name: Install Playwright browsers
      run: playwright install

    - name: Run the Python script
      run: python3 script.py

